import React, { useState, useEffect } from 'react';
import {
  View, Text, ScrollView, StyleSheet, TouchableOpacity,
  ActivityIndicator, Share, Platform
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { attendanceService } from '../services/attendanceService';
import { useAuth } from '../hooks/useAuth';

export default function ReportsScreen() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedPeriod, setSelectedPeriod] = useState('month');
  const { user } = useAuth();

  const periods = [
    { label: 'Week', value: 'week' },
    { label: 'Month', value: 'month' },
    { label: 'Semester', value: 'semester' },
  ];

  useEffect(() => {
    loadReports();
  }, [selectedPeriod]);

  const loadReports = async () => {
    setLoading(true);
    try {
      const data = await attendanceService.getReports(user.id, selectedPeriod);
      setReports(data);
    } catch (e) {
      console.log('Error loading reports', e);
    } finally {
      setLoading(false);
    }
  };

  const handleShare = async (report) => {
    try {
      await Share.share({
        message: `Attendance Report - ${report.className}\nPeriod: ${selectedPeriod}\nPresent: ${report.present}/${report.total}\nRate: ${report.rate}%\n\nGenerated by AttendIQ`,
        title: 'Attendance Report',
      });
    } catch (e) {
      console.log('Share error', e);
    }
  };

  const getRateColor = (rate) => {
    if (rate >= 75) return '#16A34A';
    if (rate >= 60) return '#D97706';
    return '#DC2626';
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <Text style={styles.pageTitle}>Attendance Reports</Text>

      {/* Period Selector */}
      <View style={styles.periodSelector}>
        {periods.map((p) => (
          <TouchableOpacity
            key={p.value}
            style={[styles.periodBtn, selectedPeriod === p.value && styles.periodBtnActive]}
            onPress={() => setSelectedPeriod(p.value)}
          >
            <Text style={[styles.periodText, selectedPeriod === p.value && styles.periodTextActive]}>
              {p.label}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      {loading ? (
        <ActivityIndicator size="large" color="#4F46E5" style={{ marginVertical: 40 }} />
      ) : reports.length === 0 ? (
        <View style={styles.emptyBox}>
          <Ionicons name="document-outline" size={48} color="#9CA3AF" />
          <Text style={styles.emptyText}>No reports available</Text>
        </View>
      ) : (
        reports.map((report, idx) => (
          <View key={idx} style={styles.reportCard}>
            <View style={styles.reportHeader}>
              <View style={{ flex: 1 }}>
                <Text style={styles.reportClass}>{report.className}</Text>
                <Text style={styles.reportCode}>{report.courseCode}</Text>
              </View>
              <View style={[styles.rateBadge, { backgroundColor: getRateColor(report.rate) + '20' }]}>
                <Text style={[styles.rateText, { color: getRateColor(report.rate) }]}>
                  {report.rate}%
                </Text>
              </View>
            </View>

            {/* Progress Bar */}
            <View style={styles.progressBar}>
              <View style={[styles.progressFill, {
                width: `${report.rate}%`,
                backgroundColor: getRateColor(report.rate),
              }]} />
            </View>

            {/* Stats Row */}
            <View style={styles.statsRow}>
              <ReportStat label="Present" value={report.present} color="#16A34A" />
              <ReportStat label="Absent" value={report.absent} color="#DC2626" />
              <ReportStat label="Total" value={report.total} color="#4F46E5" />
            </View>

            {/* Session List */}
            {report.sessions && report.sessions.length > 0 && (
              <View style={styles.sessionList}>
                <Text style={styles.sessionTitle}>Session Log</Text>
                {report.sessions.slice(0, 5).map((s, si) => (
                  <View key={si} style={styles.sessionRow}>
                    <Ionicons
                      name={s.present ? 'checkmark-circle' : 'close-circle'}
                      size={16}
                      color={s.present ? '#16A34A' : '#DC2626'}
                    />
                    <Text style={styles.sessionDate}>{s.date}</Text>
                    <Text style={[styles.sessionStatus, { color: s.present ? '#16A34A' : '#DC2626' }]}>
                      {s.present ? 'Present' : 'Absent'}
                    </Text>
                  </View>
                ))}
              </View>
            )}

            {/* Share Button */}
            <TouchableOpacity style={styles.shareBtn} onPress={() => handleShare(report)}>
              <Ionicons name="share-outline" size={16} color="#4F46E5" />
              <Text style={styles.shareText}>Share Report</Text>
            </TouchableOpacity>
          </View>
        ))
      )}
    </ScrollView>
  );
}

function ReportStat({ label, value, color }) {
  return (
    <View style={styles.reportStat}>
      <Text style={[styles.reportStatValue, { color }]}>{value}</Text>
      <Text style={styles.reportStatLabel}>{label}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F3F4F6' },
  content: { padding: 20, paddingBottom: 40 },
  pageTitle: { fontSize: 24, fontWeight: '800', color: '#111827', marginBottom: 20 },
  periodSelector: {
    flexDirection: 'row', backgroundColor: '#E5E7EB',
    borderRadius: 12, padding: 4, marginBottom: 20,
  },
  periodBtn: { flex: 1, paddingVertical: 8, borderRadius: 10, alignItems: 'center' },
  periodBtnActive: { backgroundColor: '#4F46E5' },
  periodText: { fontSize: 14, fontWeight: '600', color: '#6B7280' },
  periodTextActive: { color: '#fff' },
  emptyBox: { alignItems: 'center', padding: 40 },
  emptyText: { color: '#9CA3AF', marginTop: 10, fontSize: 14 },
  reportCard: {
    backgroundColor: '#fff', borderRadius: 16, padding: 16,
    marginBottom: 14, elevation: 2,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06, shadowRadius: 4,
  },
  reportHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  reportClass: { fontSize: 16, fontWeight: '700', color: '#111827' },
  reportCode: { fontSize: 12, color: '#9CA3AF', marginTop: 2 },
  rateBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20 },
  rateText: { fontSize: 15, fontWeight: '800' },
  progressBar: { height: 8, backgroundColor: '#E5E7EB', borderRadius: 4, marginBottom: 12 },
  progressFill: { height: 8, borderRadius: 4 },
  statsRow: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 12 },
  reportStat: { alignItems: 'center' },
  reportStatValue: { fontSize: 20, fontWeight: '800' },
  reportStatLabel: { fontSize: 11, color: '#9CA3AF', marginTop: 2, fontWeight: '600' },
  sessionList: { borderTopWidth: 1, borderTopColor: '#F3F4F6', paddingTop: 10, marginBottom: 10 },
  sessionTitle: { fontSize: 13, fontWeight: '700', color: '#374151', marginBottom: 6 },
  sessionRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 4, gap: 8 },
  sessionDate: { flex: 1, fontSize: 13, color: '#6B7280' },
  sessionStatus: { fontSize: 13, fontWeight: '600' },
  shareBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 6, paddingVertical: 10, borderTopWidth: 1, borderTopColor: '#F3F4F6',
  },
  shareText: { color: '#4F46E5', fontSize: 14, fontWeight: '600' },
});
